# Data_Preprocessing_Template

In [58]:
#importing libraries
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [59]:
#reading your data (csv,excel)
dataset= pd.read_csv('C:/Users/rashm/Desktop/ECODERS_Datasets/Pandas/all_datasets/Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Taking care of missing number from specific columns

In [60]:
# # We were using ... sklearn.preprocessing ...Imputer class
# # now we are using sklearn.impute, SimpleImputer
# from sklearn.impute import SimpleImputer
# # make an object of the SimpleImputer class
# s= SimpleImputer(missing_values= np.nan, strategy ='mean',verbose=0) # verbose means axis :- columns = 0
# # using the object  fit the columns on which you want apply this strategy
# s=s.fit(dataset[['Age','Salary']])
# dataset[['Age','Salary']]=s.transform(dataset[['Age','Salary']])
# dataset[['Age','Salary']]

In [61]:
# dataset without missing numbers NaN
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [62]:
# We were using ... sklearn.preprocessing ...Imputer class
# now we are using sklearn.impute, SimpleImputer
from sklearn.impute import SimpleImputer
# make an object of the SimpleImputer class
s= SimpleImputer(missing_values= np.nan, strategy ='mean',verbose=0) # verbose means axis :- columns = 0 rows = 1 in numpy
# using the object  fit the columns on which you want apply this strategy
s=s.fit(dataset.iloc[:,1:3])
dataset.iloc[:,1:3]=s.transform(dataset.iloc[:,1:3])
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [63]:
# # We were using ... sklearn.preprocessing ...Imputer class
# # now we are using sklearn.impute, SimpleImputer
# from sklearn.impute import SimpleImputer
# # make an object of the SimpleImputer class
# s= SimpleImputer(missing_values= np.nan, strategy ='mean',verbose=0) # verbose means axis :- columns = 0 rows = 1 in numpy
# # using the object  fit the columns on which you want apply this strategy
# s=s.fit(dataset.iloc[:,[1,2]])
# dataset.iloc[:,[1,2]]=s.transform(dataset.iloc[:,[1,2]])
# dataset

In [64]:
# step3:identifying all independent variables X
# identifying the dependent variable y (which our machine will predict)
X = dataset.iloc[:,:-1]
Y= dataset.iloc[:,3]

In [65]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [66]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

#Step4: Taking care of categorical values:- any string values have to converted into numerical value

In [67]:
Labelencoder_L= LabelEncoder()

In [68]:
X.iloc[:,0]= Labelencoder_L.fit_transform(X.iloc[:,0])
X

Country        Age        Salary
0        0  44.000000  72000.000000
1        2  27.000000  48000.000000
2        1  30.000000  54000.000000
3        2  38.000000  61000.000000
4        1  40.000000  63777.777778
5        0  35.000000  58000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
8        1  50.000000  83000.000000
9        0  37.000000  67000.000000

In [69]:
Y= Labelencoder_L.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [70]:
from sklearn.preprocessing import OneHotEncoder


In [71]:
from sklearn.compose import ColumnTransformer

In [72]:
ColumnTransformer = ColumnTransformer([('encoder',OneHotEncoder(), [0])],remainder='passthrough')
dataset = np.array(ColumnTransformer.fit_transform(dataset),dtype= np.str)
dataset

array([['1.0', '0.0', '0.0', '44.0', '72000.0', 'No'],
       ['0.0', '0.0', '1.0', '27.0', '48000.0', 'Yes'],
       ['0.0', '1.0', '0.0', '30.0', '54000.0', 'No'],
       ['0.0', '0.0', '1.0', '38.0', '61000.0', 'No'],
       ['0.0', '1.0', '0.0', '40.0', '63777.77777777778', 'Yes'],
       ['1.0', '0.0', '0.0', '35.0', '58000.0', 'Yes'],
       ['0.0', '0.0', '1.0', '38.77777777777778', '52000.0', 'No'],
       ['1.0', '0.0', '0.0', '48.0', '79000.0', 'Yes'],
       ['0.0', '1.0', '0.0', '50.0', '83000.0', 'No'],
       ['1.0', '0.0', '0.0', '37.0', '67000.0', 'Yes']], dtype='<U17')

In [73]:
y=dataset[:,5]

In [74]:
y=Labelencoder_L.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

Step5:- Splitting the data into training and testing data set

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2,random_state=0)

In [77]:
X_train

Country        Age        Salary
4        1  40.000000  63777.777778
9        0  37.000000  67000.000000
1        2  27.000000  48000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
3        2  38.000000  61000.000000
0        0  44.000000  72000.000000
5        0  35.000000  58000.000000

In [78]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

# Step6: feature Scaling

# Standardization formula
#  Xstand = X- mean(X) / sd(X)
# Normalizationformula
# Xnorm = X - min(x) / (max(x) - min(x))

In [79]:
from sklearn.preprocessing import StandardScaler

In [80]:
sc_x = StandardScaler()

In [81]:
X_train = sc_x.fit_transform(X_train )
X_test = sc_x.fit_transform(X_test)
X_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [82]:
X_train = sc_x.fit_transform(X_train )
X_test = sc_x.fit_transform(X_test)
X_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [83]:
sc_y = StandardScaler()